[tool.poetry]
packages = [{include = "components"}]

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100

ignore = ["E402", "F401"]
unfixable = []

per-file-ignores = {}


pythonpath = ["."]

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
